### Listar productos activos
GET http://localhost:3000/productos

### Crear un producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "categoria_id": 1,
  "nombre": "Tostado queso y tomate",
  "tipo": "simple"
}

### Obtener un producto por id
GET http://localhost:3000/productos/1

### Actualizar un producto
PUT http://localhost:3000/productos/1
Content-Type: application/json

{
  "categoria_id": 1,
  "nombre": "Helado 1/4 kg (editado)",
  "tipo": "simple"
}

### Desactivar (soft-delete) un producto
DELETE http://localhost:3000/productos/6


### Historial de precios de un producto
GET http://localhost:3000/productos/8/precios

### Agregar un precio nuevo
POST http://localhost:3000/productos/9/precios
Content-Type: application/json

{
  "canal_id": 1,
  "monto": 17500
}


### Debería fallar: falta el nombre
POST http://localhost:3000/productos
Content-Type: application/json

{
  "categoria_id": 1,
  "tipo": "simple"
}
